@payzen_backend_HostAddress = http://localhost:5119
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbkBwYXl6ZW4uY29tIiwidWlkIjoiMSIsImVtYWlsIjoiYWRtaW5AcGF5emVuLmNvbSIsImp0aSI6Ijc0MGQ5YjEyLWQ4NDQtNDY3NS1hNjU3LWE3OTE1ODNiYjAyNyIsImV4cCI6MTc2NDE1NTg3MiwiaXNzIjoiUGF5emVuQXBpIiwiYXVkIjoiUGF5emVuQXBwIn0.34b5QV3vVedi3qjRzNFbi_QS8rI_sEDp8zYVEbEZmI0

###
# Test Login
POST {{payzen_backend_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "Email": "admin@payzen.com",
  "Password": "12345678"
}
###
# CRUD Users
# User doie être authentifié
# Test CREATE user
POST {{payzen_backend_HostAddress}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Username": "john.doe",
  "Email": "john.doe@payzen.com",
  "Password": "SekretPass123",
  "IsActive": true
}
###
# Test READ users
GET {{payzen_backend_HostAddress}}/api/users
Authorization: Bearer {{token}}
###
# Test READ single user by ID
@user_id = 7
GET {{payzen_backend_HostAddress}}/api/users/{{user_id}}
Authorization: Bearer {{token}}
###
# Test UPDATE user
PUT {{payzen_backend_HostAddress}}/api/users/{{user_id}}
Authorization: Bearer {{token}}
{
  "Email": "john.doe.updated@payzen.com",
  "IsActive": true
}
###
# Test DELETE user (Soft delete)
DELETE {{payzen_backend_HostAddress}}/api/users/{{user_id}}
Authorization: Bearer {{token}}
###
# Test Get pour vérification user n'apparait plus
GET {{base_url}}/api/users/{{new_user_id}}
Authorization: Bearer {{token}}

###
# CRUD Permissions
# Test CREATE Permission
POST {{payzen_backend_HostAddress}}/api/permissions
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "CREATE_USERS",
  "Description": "Permet de créer de nouveaux utilisateurs"
}
###
# Test READ ALL Permission
GET {{payzen_backend_HostAddress}}/api/permissions
Authorization: Bearer {{token}}
Content-Type: application/json
###
# test READ une seul Permission
@permission_id = 10
GET {{payzen_backend_HostAddress}}/api/permissions/{{permission_id}}
Authorization: Bearer {{token}}
Content-Type: application/json
###
# test UPDATE Permission
PUT {{base_url}}/api/permissions/{{permission_create_users}}
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Description": "Permet de créer et enregistrer de nouveaux utilisateurs dans le système"
}